language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
deploy:
  provider: npm
  email: nwoltman@outlook.com
  api_key:
    secure: RvbWk+aLjEsXDxR7Polxd1+4J9KVryTeYBcqXS37m0m0DkX0tb+GQfn3F0t04b3QpjueMkOGyMt25VbJgwy5PHvfCcQBn7CJ0saryxsEkLhXTGlbaMWNHv/UbEKqGNs8s5MoLg7CYWL9r02/HqQiBdPzNO24kq+oMOF91I+71r4=
  on:
    tags: true
